version: "3.7"

services:
  bazarr:
    image: linuxserver/bazarr:amd64-latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - bazarr-config:/config
      - ${PLEX_MOVIES_DIR}:/movies
      - ${PLEX_TV_DIR}:/tv
    expose:
      - 6767
    networks:
      - media
      - reverse-proxy
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:amd64-latest
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - jackett-config:/config
    expose:
      - 9117
    networks:
      - media
      - reverse-proxy
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - TZ=${TZ}
      - LOG_LEVEL=info
    expose:
      - 5055
    volumes:
      - overseerr-config:/app/config:rw
    networks:
      - media
      - reverse-proxy
    restart: unless-stopped

  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    network_mode: host
    environment:
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - plex-config:/config
      - ${PLEX_MOVIES_DIR}:/movies
      - ${PLEX_MOVIES_4K_DIR}:/movies-4k
      - ${PLEX_PREROLLS_DIR}:/prerolls
      - /dev/shm:/transcode
      - ${PLEX_TV_DIR}:/tv
      - ${PLEX_TV_4K_DIR}:/tv-4k
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:amd64-nightly-4.1.0.6176-ls280
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - radarr-config:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${PLEX_MOVIES_DIR}:/movies
    expose:
      - 7878
    networks:
      - media
      - reverse-proxy
      - torrent
    restart: unless-stopped

  radarr-4k:
    image: linuxserver/radarr:amd64-nightly-4.1.0.6176-ls280
    container_name: radarr-4k
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - radarr-4k-config:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${PLEX_MOVIES_4K_DIR}:/movies
    expose:
      - 7878
    networks:
      - media
      - reverse-proxy
      - torrent
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - sonarr-config:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${PLEX_TV_DIR}:/tv
    expose:
      - 8989
    networks:
      - media
      - reverse-proxy
      - torrent
    restart: unless-stopped

  sonarr-4k:
    image: linuxserver/sonarr:latest
    container_name: sonarr-4k
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - sonarr-4k-config:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${PLEX_TV_4K_DIR}:/tv
    expose:
      - 8989
    networks:
      - media
      - reverse-proxy
      - torrent
    restart: unless-stopped

  tautulli:
    image: linuxserver/tautulli:amd64-latest
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - tautulli-config:/config
    expose:
      - 8181
    networks:
      - media
      - reverse-proxy
      - torrent
    restart: unless-stopped

volumes:
  bazarr-config:
    name: bazarr-config
  jackett-config:
    name: jackett-config
  plex-config:
    name: plex-config
  radarr-config:
    name: radarr-config
  radarr-4k-config:
    name: radarr-4k-config
  sonarr-config:
    name: sonarr-config
  sonarr-4k-config:
    name: sonarr-4k-config
  overseerr-config:
    name: overseerr-config
  tautulli-config:
    name: tautulli-config

networks:
  media:
    name: media
  reverse-proxy:
    external: true
  torrent:
    external: true
